/*
 * @Author: liwz
 * @Date: 2024-09-18 10:53:39
 * @LastEditors: liwz
 * @LastEditTime: 2024-09-18 18:17:18
 * @FilePath: /study_new/table-explore/src/components/tableExplore.js
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
 */

export const tableData = [
  {
    province: '山东',
    county: '成武',
    products: '数码电子',
    product: '单反相机',
    provinceRowspan: 8,
    countyRowspan: 4,
    productsRowspan: 2,
    product: '单反相机',
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '成武',
    products: '数码电子',
    product: '小计',
    // countyRowspan: 4,
    // productsRowspan: 2,
    // productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '成武',
    products: '数码电子',
    product: '单反相机',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    productsRowspan: 2,
    // productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '成武',
    products: '数码电子',
    product: '小计',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    // productsRowspan: 2,
    // productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '威海',
    products: '数码电子',
    product: '单反相机',
    provinceRowspan: 8,
    countyRowspan: 4,
    productsRowspan: 2,
    product: '单反相机',
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '威海',
    products: '数码电子',
    product: '小计',
    // countyRowspan: 4,
    // productsRowspan: 2,
    // productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '威海',
    products: '数码电子',
    product: '单反相机',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    productsRowspan: 2,
    // productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '山东',
    county: '威海',
    products: '数码电子',
    product: '小计',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    // productsRowspan: 2,
    productRowspan: 1,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '河南',
    county: '郑州',
    products: '户外运动',
    product: '乒乓球',
    provinceRowspan: 4,
    countyRowspan: 4,
    // productsRowspan: 2,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '河南',
    county: '郑州',
    products: '户外运动',
    product: '小计',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '河南',
    county: '郑州',
    products: '户外运动',
    product: '篮球',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    productsRowspan: 2,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  },
  {
    province: '河南',
    county: '郑州',
    products: '户外运动',
    product: '小计',
    // provinceRowspan: 4,
    // countyRowspan: 4,
    oneSales: 100,
    oneProfit: 101,
    twoSales: 201,
    twoProfit: '202',
    threeSales: '301',
    threeProfit: '302',
    oneSalesTotal: '1000',
    oneProfitTotal: '1000',
    fourSales: '',
    fourProfit: '',
    fiveSales: '',
    fiveProfit: '',
    sixSales: '',
    sixProfit: '',
    towSalesTotal: 0,
    twoProfitTotal: 0
  }
]
